apiVersion: sources.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-timer-source
  namespace: kn-demo 
spec:
  source:
    flow:
      from:
        uri: 'timer:tick?period=3000'
        steps:
          - set-body:
              constant: Hello World!
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: msgtxr-sl
