apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: event-dumpy-subscriber 
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-dumpy
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: dumpy-serverless 
