apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: msgtxr-subscriber 
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: imc-msgtxr
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: msgtxr-sl
