apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource 
metadata:
  name: event-dumpy-cronjob-source
spec:
  schedule: "* * * * *"
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-dumpy
