apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: dumpy-trigger
spec:
  filter:
    sourceAndType:
      type: dev.knative.eventing.samples.heartbeat
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: dumpy-serverless
