apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: ch-event-dumpy
spec:
  provisioner: 
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory
