apiVersion: sources.knative.dev/v1alpha2
kind: PingSource 
metadata:
  name: msgtxr-pingsource
spec:
  jsonData: This message is from PingSource
  schedule: '* * * * *'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: msgtxr-sl
      namespace: kn-demo
