apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: event-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel     
    name: testchannel-one
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: msgtxr-sl       
