apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers: 
   - my-cluster-kafka-bootstrap.kafka:9092 
  topics: 
   - knative-demo-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: msgtxr-sl
